### ISSUE TITLE
Option to disable the HQ->NQ stack reduction feature

### ISSUE THREAD

**Issue by DAOWAce** [giulianoriccio/retain-me-not#5]
One of the things added was this feature.  Listed as:
> Consider the option of lowering the quality of HQ items to stack them together with NQ items

While a good feature for those who actually want to reduce the HQ items, I personally don't, and I've taken to using that portion of the page for looking for item stack dupes I've put on different retainers.  The items will be listed as a stack of 3 (or more), and I've gotta number hunt to find them in the list.

I am wondering if it would be easy to add a toggle for listing these, so we're able to see only duplicates to make it easy to combine things split across multiple retainers.

**Comment by giulianoriccio** [comment]
@DAOWAce I've added the option. It's on by default so you have to disable it to hide the quality lowering from the report.
