### ISSUE TITLE
Will the extension get ported to use XIVAPP

### ISSUE THREAD

**Issue by Tataru-Taru** [giulianoriccio/retain-me-not#6]
With XIVDB dying at the start of the month, do you have any plans to rerelease the extension to use the XIV API instead?

I love the extension but worry it will no longer feature all the items.

**Comment by giulianoriccio** [comment]
I didn't know it was shutting down. I'll replace the API as soon as possible.

For now the plugin will keep working with the data it has stored in the browser.

**Comment by giulianoriccio** [comment]
@Tataru-Taru I've submitted the new version for Chrome and Firefox. Firefox is already published while Chrome should be available soon.

**Comment by Tataru-Taru** [comment]
Thank you for your work :D
