### ISSUE TITLE
Extension no longer showing data on retainer pages

### ISSUE THREAD

**Issue by mheimbig** [giulianoriccio/retain-me-not#7]
I've used retain-me-not in the past (been a number of months, though) and had no issues. When I loaded it up today, it doesn't appear to be loading into my retainer inventory pages on the Lodestone, nor am I getting the Retain Me Not tab. I've attempted to use in Chrome 71.0.3578.98 and Firefox 64.0.2 and RMN 1.2.0 (installed from the respective stores). Firefox is a fresh install on my system to check if it was a Chrome-specific issue. Both browsers exhibit the same behavior (screenshot below). Is there something I'm missing?
Thank you!
![image](https://user-images.githubusercontent.com/96577/51212357-8d588480-18d5-11e9-9257-eded4fd61750.png)

**Comment by giulianoriccio** [comment]
I'm sorry that it's not working. XIVDB is dead so there is no data available for it to work.

I'm replacing the data with XIVAPI's but it's taking me a bit of time because what I used to match the items is not available anymore. I should release a working replacement between a couple of days.

**Comment by giulianoriccio** [comment]
duplicate of #6

**Comment by giulianoriccio** [comment]
Duplicate of #6

**Comment by mheimbig** [comment]
My apologies! I completely forgot that XIVDB has already shut down. No rush. I appreciate the response!

**Comment by giulianoriccio** [comment]
@mheimbig I've submitted the new version for Chrome and Firefox. Firefox is already published while Chrome should be available soon.
